---
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      after_success: "pipenv run codecov"
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.8-dev"
      dist: xenial
      sudo: true
      if: branch = dev AND type = push
  allow_failures:
    - python: "3.8-dev"
      dist: xenial
      sudo: true

cache:
  directories:
    - $HOME/.cache/pip
install: "make init"
language: python
script: "pipenv run make ci"
