---
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
    - python: "3.6"
      after_success: "pipenv run codecov"
    - python: "3.7"
      dist: xenial

language: python
install: "make init"
script: "pipenv run make ci"
cache: "pip"
