---
sudo: false
language: python
python:
  - "3.5"
  - "3.6"
matrix:
include:
  - python: 3.7
    dist: xenial
    sudo: true
install: "make init"
script: "pipenv run make ci"
cache: "pip"
jobs:
  include:
    - stage: "coverage"
      python: "3.6"
      script: "pipenv run codecov"
